# Generated by Django 3.1.3 on 2020-11-06 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Login',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trinity_id', models.CharField(max_length=200)),
                ('trinity_password', models.CharField(max_length=500)),
            ],
        ),
    ]
